import { getIsInPast, getIsToday } from 'src/utils/date';

export type EventItemType = {
  name: string;
  location: string;
  image: string;
  startDate: string;
  endDate: string;
  conferenceUrl?: string;
  latlon?: [number, number];
  mapIcon?: {
    url: string;
    rounded?: boolean;
  };
};

const allEvents = [
  {
    name: 'ETHToronto',
    startDate: 'August 8, 2022',
    endDate: 'August 10, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.ethtoronto.ca/',
    latitude: '',
    longitude: '',
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'Blockchain Futurist Conference, Toronto, Canada',
    startDate: 'August 9, 2022',
    endDate: 'August 10, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.futuristconference.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'events@untraceableinc.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Futurist_conf/',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHMexicoCity',
    startDate: 'August 19, 2022',
    endDate: 'August 21, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://mexico.ethglobal.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@ethglobal.com partner@ethglobal.com',
    LinkedIn: 'https://www.linkedin.com/company/ethglobal/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ethereum_mexico https://twitter.com/ethglobal',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'CoinFest Asia (Bali, Indonesia)',
    startDate: 'August 25, 2022',
    endDate: 'August 26, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://coinfest.asia/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hi@coinfest.asia',
    LinkedIn: 'https://www.linkedin.com/showcase/coinfest/',
    Suitable: 'No',
    Telegram: 'https://t.me/CoinfestAsia',
    Twitter: 'https://twitter.com/coinfestasia',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'EDCON, San Francisco',
    startDate: 'August 28, 2022',
    endDate: 'August 28, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://go.ueth.org/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/EDCON_Online',
    Youtube: '',
    '📮': ''
  },
  {
    name: "The Science of Blockchain Conference 2022(SBC'22), Stanford",
    startDate: 'August 29, 2022',
    endDate: 'August 31, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://cbr.stanford.edu/sbc22/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/CBRStanford',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'BlockchaIn Rio Festival, Rio de Janeiro',
    startDate: 'September 1, 2022',
    endDate: 'September 4, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.blockchainrio.com.br/en-gb',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'blockchainrio@blockchainrio.com.br',
    LinkedIn: 'https://linkedin.com/company/blockchain-rio',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/blockchain_rio',
    Youtube: 'https://youtube.com/channel/UC3OfGYAJ7K6usXYVKZ5fSKw',
    '📮': 'email'
  },
  {
    name: 'ETHWarsaw',
    startDate: 'September 1, 2022',
    endDate: 'September 4, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.ethwarsaw.dev/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'In touch',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://linkedin.com/company/ethwarsaw',
    Suitable: 'No',
    Telegram: 'https://t.me/joinethwarsaw',
    Twitter: 'https://twitter.com/ETHWarsaw/',
    Youtube: 'https://www.youtube.com/c/ETHWarsaw',
    '📮': 'typeform'
  },
  {
    name: 'ETHOnline',
    startDate: 'September 2, 2022',
    endDate: 'September 28, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://online.ethglobal.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@ethglobal.com',
    LinkedIn: 'https://www.linkedin.com/company/ethglobal/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHGlobal',
    Youtube: 'https://www.youtube.com/c/ETHGlobal/',
    '📮': ''
  },
  {
    name: 'Baltic HoneyBadger 2022, Riga',
    startDate: 'September 3, 2022',
    endDate: 'September 4, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://baltichoneybadger.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@baltichoneybadger.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/baltichoneybadger',
    Twitter: 'https://twitter.com/hodlhodl',
    Youtube: 'https://www.youtube.com/c/HodlHodl',
    '📮': 'email'
  },
  {
    name: 'Digital Nomad Expo',
    startDate: 'September 6, 2022',
    endDate: 'September 7, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://dn-expo.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/digital-nomad-expo/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/NomadExpo',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'MCON 2, Denver CO',
    startDate: 'September 6, 2022',
    endDate: 'September 9, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.mcon.fun/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/mcon_world',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'CryptoVerse Expo #2 (Poland, Warsaw)',
    startDate: 'September 9, 2022',
    endDate: 'September 9, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://cryptoverseexpo.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@cryptoverseexpo.com',
    LinkedIn: 'https://www.linkedin.com/company/cryptoverse-expo/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/CryptoverseExpo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'EthereumSP, São Paulo',
    startDate: 'September 9, 2022',
    endDate: 'September 11, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.ethereumbrasil.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/jVGzRW4n27',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/ethereumbrasil/',
    Suitable: 'No',
    Telegram: 'https://t.me/Ethereum_Brasil',
    Twitter: 'https://twitter.com/Ethereum_Brasil',
    Youtube: 'https://www.youtube.com/c/EthereumBrasil',
    '📮': ''
  },
  {
    name: 'NEARCON 2022, Lisbon',
    startDate: 'September 11, 2022',
    endDate: 'September 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://nearcon.org/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/nearcon22',
    Twitter: '',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'Metaweek Summit 2022, Dubai',
    startDate: 'September 11, 2022',
    endDate: 'September 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.themetaweek.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/metaweek',
    Suitable: 'No',
    Telegram: 'https://t.me/+cAoACKqUt4RkYmQ0',
    Twitter: 'https://twitter.com/themetaweek',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'Berlin Blockchain Week',
    startDate: 'September 12, 2022',
    endDate: 'September 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://blockchainweek.berlin',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/BerlinBlockchainWeek',
    Twitter: 'https://twitter.com/BerBlockWeek',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'DappCon2022, Berlin',
    startDate: 'September 12, 2022',
    endDate: 'September 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.dappcon.io/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/kY3pPUjnt8',
    Email: 'info@gnosis-gmbh.de',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/dappcon_berlin',
    Youtube: 'https://www.youtube.com/channel/UCruCCeCNWBAM7JI-xAMtXpQ',
    '📮': ''
  },
  {
    name: 'Digital Asset Summit, NYC',
    startDate: 'September 13, 2022',
    endDate: 'September 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://blockworks.co/events/digital-asset-summit-2022-new-york/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@blockworks.co',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Blockworks_',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'CV Summit 2022, Zug Switzerland',
    startDate: 'September 14, 2022',
    endDate: 'September 15, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.blockchainsummit.ch',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@cvvc.com',
    LinkedIn: 'https://www.linkedin.com/company/cv-labs/',
    Suitable: 'No',
    Telegram: 'https://twitter.com/CV_Labs',
    Twitter: '',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'https://blockchain-life.com/europe/en/, Moscow',
    startDate: 'September 14, 2022',
    endDate: 'September 15, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://blockchain-life.com/europe/en/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email:
      'support@blockchain-life.com partnership@blockchain-life.com speakers@blockchain-life.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/blockchainlife',
    Twitter: 'https://twitter.com/BlLife_Forum',
    Youtube: 'https://www.youtube.com/channel/UCWmwg8fsoOXmW0-xAFXFeWQ/featured',
    '📮': ''
  },
  {
    name: 'Web3 In Travel Summit 2022, Porto Portugal',
    startDate: 'September 14, 2022',
    endDate: 'September 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://web3intravel.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'Frens',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/tripscommunity',
    Youtube: 'xhttps://www.youtube.com/playlist?list=PL95tqwO7E-SJYIJAQhzIwqfnOzL5_VStg',
    '📮': ''
  },
  {
    name: 'Æternity Universe Two, Laucha an der Unstrut Germany',
    startDate: 'September 15, 2022',
    endDate: 'September 16, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://aeternityuniverse.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@aeternityuniverse.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/+8O0jVxwFWc4xMjYy',
    Twitter: 'https://twitter.com/aeternity',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Die Bitcoin Konferenz, Innsbruck Austria',
    startDate: 'September 15, 2022',
    endDate: 'September 17, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://bconf.de/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/thebconf/',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'DuneCon',
    startDate: 'September 15, 2022',
    endDate: 'September 15, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.dunecon.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.com/invite/ErrzwBz',
    Email: 'support@dune.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/i/newsletters/subscribe/DuneAnalytics',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Ethereum Zurich',
    startDate: 'September 16, 2022',
    endDate: 'September 16, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.ethree.ch/ethereumzurich/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@ethree.ch',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHBerlin³',
    startDate: 'September 16, 2022',
    endDate: 'September 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://ethberlin.ooo/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'henlo@ethberlin.ooo',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHBerlin',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Australian Crypto Convention, Gold Coast, Australia',
    startDate: 'September 17, 2022',
    endDate: 'September 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.auscryptocon.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@auscryptocon.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/AusCryptoCon',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'NFT Show Europe 2022 (Valencia, Spain)',
    startDate: 'September 17, 2022',
    endDate: 'September 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://nftshoweurope.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@nftshoweurope.com',
    LinkedIn: 'https://www.linkedin.com/company/nftse/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/nftshoweurope',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHSafari, Kenya',
    startDate: 'September 18, 2022',
    endDate: 'September 24, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://ethsafari.xyz/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/CkMF5Ff83f',
    Email: 'info@ethsafari.xyz',
    LinkedIn: 'https://www.linkedin.com/company/ethsafari/',
    Suitable: 'No',
    Telegram: 'https://t.me/ethsafari',
    Twitter: 'https://twitter.com/EthSafari',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Cryptoberfest, Munich Germany',
    startDate: 'September 20, 2022',
    endDate: 'September 22, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.cryptoberfest.de/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Crypt0berfest',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Blockchain Expo Europe, Netherlands Amsterdam',
    startDate: 'September 20, 2022',
    endDate: 'September 21, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.blockchain-expo.com',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'blockchain@techexevent.com',
    LinkedIn: 'https://www.linkedin.com/groups/8267411',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Blockchain_Expo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Solana Hacker House, Singapore',
    startDate: 'September 21, 2022',
    endDate: 'September 25, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://solana.com/events/singapore-hh',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/hackerhouses',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Mainnet by Messari, NYC',
    startDate: 'September 21, 2022',
    endDate: 'September 23, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://mainnet.events/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'events@messari.io',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/+41_fGKOyW1xmNDE0',
    Twitter: 'https://twitter.com/messaricrypto',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'Zebu Live - London Web3 Conference',
    startDate: 'September 22, 2022',
    endDate: 'September 23, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.zebulive.xyz/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/fDQpJak9Bf',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/zebu-digital/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/zebu_live',
    Youtube: 'https://www.youtube.com/channel/UC1OZVqibm8P6zi3-a0NZ62Q',
    '📮': 'typeform'
  },
  {
    name: 'ETHSantiago, Chile',
    startDate: 'September 23, 2022',
    endDate: 'September 24, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://ethsantiago.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'ethsantiago@blockchainsummit.la',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/EthereumSTGO',
    Twitter: 'https://twitter.com/EthereumStgo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Cosmoverse, Medellín Colombia',
    startDate: 'September 27, 2022',
    endDate: 'September 28, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://cosmoverse.org/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'Cosmoverse@cosmoverse.org',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/joinchat/MZRLJjZngShlZGQ6',
    Twitter: 'https://twitter.com/CosmoverseHQ',
    Youtube: 'https://www.youtube.com/channel/UCRTDSU2mFSTZGYZ_SQY64tw/',
    '📮': 'email'
  },
  {
    name: 'Converge22, San Francisco',
    startDate: 'September 27, 2022',
    endDate: 'September 30, 2022',
    location: '',
    image: '',
    conferenceUrl:
      'https://converge.circle.com/event/4ea0d06f-3900-4b6d-a9cd-aeaedda9ef2e/summary',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'converge@circle.com',
    LinkedIn: 'https://www.linkedin.com/company/circle-internet-financial',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/circlepay',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Immerse Global Summit Europe 2022 (Funchal, Madeira Island, Portugal)',
    startDate: 'September 28, 2022',
    endDate: 'September 30, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.immerseglobalnetwork.com/igs-europe',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'http://www.linkedin.com/company/vr-ar-global-summit',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ImmerseSummit',
    Youtube: 'https://www.youtube.com/c/VRARAssociation/',
    '📮': 'typeform'
  },
  {
    name: 'SmartCon, NYC',
    startDate: 'September 28, 2022',
    endDate: 'September 29, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://smartcon.chain.link/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'smartcon@chain.link',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/chainlink',
    Youtube: 'https://www.youtube.com/chainlink',
    '📮': 'email'
  },
  {
    name: 'Token2049, Singapore',
    startDate: 'September 28, 2022',
    endDate: 'September 29, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.asia.token2049.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': 'mailto:joyce@token2049.com',
    Connection: 'No',
    'Contact person (CP)': 'Joyce',
    Discord: '',
    Email: 'info@token2049.com',
    LinkedIn: 'https://www.linkedin.com/company/token2049/',
    Suitable: 'No',
    Telegram: 'https://t.me/token2049official',
    Twitter: 'https://twitter.com/token2049',
    Youtube: 'https://www.youtube.com/c/TOKEN2049',
    '📮': 'email'
  },
  {
    name: 'Solana Hacker House, Bogota Colombia',
    startDate: 'October 4, 2022',
    endDate: 'October 8, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://solana.com/events/bogota-hacker-house',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Blockchain Economy, Dubai',
    startDate: 'October 4, 2022',
    endDate: 'October 5, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://beconomydubai.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@teklip.org',
    LinkedIn: 'https://www.linkedin.com/company/teklip',
    Suitable: 'No',
    Telegram: 'https://t.me/BE2020_Istanbul',
    Twitter: 'https://twitter.com/BEconomy_HQ',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Blockchain Land, Monterrey Mexico',
    startDate: 'October 5, 2022',
    endDate: 'October 7, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://blockchain-land.io/en/home/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@talent-network.org',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.co/pADJdLwdRz',
    Twitter: 'https://twitter.com/blockchain_land',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Crypto Expo, Dubai',
    startDate: 'October 5, 2022',
    endDate: 'October 6, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://cryptoexpodubai.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@cryptoexpodubai.com',
    LinkedIn: 'https://www.linkedin.com/company/cryptoexpo/',
    Suitable: 'No',
    Telegram: 'https://telegram.me/dwainCED',
    Twitter: 'https://twitter.com/TheCryptoExpo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Blockchain Expo North America, Santa Clara CA',
    startDate: 'October 5, 2022',
    endDate: 'October 6, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://blockchain-expo.com/northamerica/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'blockchain@techexevent.com',
    LinkedIn: 'https://www.linkedin.com/company/blockchain-expo/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Blockchain_Expo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'DeFi Conf 2022, Belfast UK',
    startDate: 'October 6, 2022',
    endDate: 'October 6, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://deficonf.xyz/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@deficonf.xyz',
    LinkedIn:
      'https://www.linkedin.com/company/defi-conf-decentralised-finance-conference',
    Suitable: 'No',
    Telegram: 'https://t.me/deficonf',
    Twitter: 'https://twitter.com/DeFi_Conf',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Devcon week (Bogotá)',
    startDate: 'October 7, 2022',
    endDate: 'October 16, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://devcon.org/en/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://t.me/devcon_bogota',
    Email: 'support@devcon.org',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/devcon_bogota',
    Twitter: 'https://twitter.com/EFDevcon',
    Youtube: 'https://www.youtube.com/c/EthereumFoundation/search?query=devcon',
    '📮': ''
  },
  {
    name: 'InfiniteHackETH',
    startDate: 'October 7, 2022',
    endDate: 'October 9, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://infinite-hackathons.eth.limo/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.com/invite/svYyMwj9Jv',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/InfiniteHackETH',
    Youtube: '',
    '📮': 'twitter'
  },
  {
    name: 'ETHBogota',
    startDate: 'October 7, 2022',
    endDate: 'October 9, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://bogota.ethglobal.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'partner@ethglobal.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHGlobal/',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'WOW Summit, Dubai, UAE',
    startDate: 'October 8, 2022',
    endDate: 'October 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://wowsummit.net/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'INFO@WOWSUMMIT.NET',
    LinkedIn: 'https://www.linkedin.com/showcase/wow-summit-world/',
    Suitable: 'No',
    Telegram: 'https://t.me/wowsummitworld',
    Twitter: 'https://twitter.com/wowsummitworld',
    Youtube: 'https://www.youtube.com/channel/UCooGWgLOF9sHQo69GhLmY2w/videos',
    '📮': ''
  },
  {
    name: 'Crypto Business Conference, San Diego',
    startDate: 'October 9, 2022',
    endDate: 'October 11, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.socialmediaexaminer.com/cbconference/hotel/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: '5th Future Blockchain Summit, Dubai',
    startDate: 'October 10, 2022',
    endDate: 'October 13, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.futureblockchainsummit.com/home',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': 'Steven.Besse@dwtc.com',
    Connection: 'No',
    'Contact person (CP)': 'Steven Besse',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/showcase/future-blockchain-summit1',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/dxbontheblock',
    Youtube: 'https://www.youtube.com/c/FutureBlockchainSummit/',
    '📮': 'email'
  },
  {
    name: 'Stellar Meridian, Rome Italy',
    startDate: 'October 11, 2022',
    endDate: 'October 13, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://meridian.stellar.org/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/stellar-development-foundation/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/stellarorg',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Ethereum DevCon VI | Bogotá',
    startDate: 'October 11, 2022',
    endDate: 'October 14, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://devcon.org/en/bogota/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.com/invite/FhmA3KeF3B',
    Email: 'support@devcon.org',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/devcon_bogota',
    Twitter: 'https://twitter.com/efdevcon',
    Youtube: 'https://www.youtube.com/c/EthereumFoundation/search?query=devcon',
    '📮': ''
  },
  {
    name: 'LA Blockchain Summit',
    startDate: 'October 12, 2022',
    endDate: 'October 13, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://lablockchainsummit.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/cryptoinvestsummit',
    Twitter: 'https://twitter.com/lablockchainsmt',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'TABConf, Atlanta GA',
    startDate: 'October 14, 2022',
    endDate: 'October 15, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://2022.tabconf.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/TxFAWb3Adp',
    Email: 'hello@tabconf.com',
    LinkedIn: 'https://www.linkedin.com/company/tabconf',
    Suitable: 'No',
    Telegram: 'https://t.me/tabconf',
    Twitter: 'https://twitter.com/tabconf',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'World Blockchain Summit, Dubai',
    startDate: 'October 17, 2022',
    endDate: 'October 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://worldblockchainsummit.com/dubai/index',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@worldblockchainsummit.com',
    LinkedIn: 'https://www.linkedin.com/company/tresconglobal/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/tresconglobal',
    Youtube: 'https://www.youtube.com/channel/UC3ItPPc9UdFxo0-zx2oNOfQ',
    '📮': ''
  },
  {
    name: 'Merge 2022, London',
    startDate: 'October 17, 2022',
    endDate: 'October 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.fintechnexus.com/merge/2022/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@fintechnexus.com',
    LinkedIn: 'https://www.linkedin.com/company/fintech-nexus/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Fintechnexus',
    Youtube: 'http://youtube.com/fintechnexus',
    '📮': ''
  },
  {
    name: 'Blockworks, London',
    startDate: 'October 17, 2022',
    endDate: 'October 18, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://blockworks.co/events/digital-asset-summit-2022-london/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'http://discord.gg/blockworks',
    Email: 'events@blockworks.co',
    LinkedIn: 'https://www.linkedin.com/company/the-blockworks-group',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Blockworks_ https://twitter.com/BlockworksDAS',
    Youtube: 'https://www.youtube.com/c/BlockWorksGroup/videos',
    '📮': 'email'
  },
  {
    name: 'D2: Decentralization Deciphered Summit, New York',
    startDate: 'October 18, 2022',
    endDate: 'October 19, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://d2.live/https://d2.live/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/d2-decentralization-deciphered/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/D2Web3',
    Youtube: 'https://www.youtube.com/channel/UC2xMJSOxc5szlfdHnp8S7fg/',
    '📮': ''
  },
  {
    name: 'ETH Medellin',
    startDate: 'October 18, 2022',
    endDate: 'October 22, 2022',
    location: '',
    image: '',
    conferenceUrl: 'ethmedellin.co',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/EthMedellin',
    Youtube: '',
    '📮': 'chat'
  },
  {
    name: 'Augmented Enterprise Summit 2022, San Diego CA',
    startDate: 'October 18, 2022',
    endDate: 'October 20, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://augmentedenterprisesummit.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'support@brainxchange.events',
    LinkedIn: 'https://www.linkedin.com/company/brainxchange-llc/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/BrainXchange',
    Youtube: 'https://www.youtube.com/c/BrainXchange/videos',
    '📮': 'email'
  },
  {
    name: 'Vietnam Blockchain Summit 2022',
    startDate: 'October 19, 2022',
    endDate: 'October 20, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.vietnamblockchainsummit.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@vietnamblockchainsummit.com',
    LinkedIn: 'https://www.linkedin.com/company/81816352/admin/',
    Suitable: 'No',
    Telegram: 'https://t.me/+31tDdeJqu3c0ZTM1',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'CryptoFest 2022, Dubai',
    startDate: 'October 19, 2022',
    endDate: 'October 20, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://cryptofestdubai.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@gulfxellence.com',
    LinkedIn: 'https://www.linkedin.com/company/gulfxellence/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/gxellence',
    Youtube: 'https://www.youtube.com/c/GulfXellence',
    '📮': ''
  },
  {
    name: 'Canadian Blockchain Summit, Calgary',
    startDate: 'October 19, 2022',
    endDate: 'October 20, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.canadablockchain.ca/canadian-blockchain-summit/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@canadablockchain.ca',
    LinkedIn: 'https://www.linkedin.com/company/albertablockchain',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Blockchain_ABC',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'The MarTech Summit, Bangkok Thailand',
    startDate: 'October 19, 2022',
    endDate: 'October 20, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://themartechsummit.com/bangkok',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@themartechsummit.com',
    LinkedIn: 'https://www.linkedin.com/showcase/the-martech-summit',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Martech_Summit',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ELEV8CON Parabolic, Las Vegas, NV',
    startDate: 'October 21, 2022',
    endDate: 'October 23, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://elev8con.com/elev8con/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/elev8con/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ELEV8con',
    Youtube: 'https://www.youtube.com/channel/UCOUb07WLFjEIFEWfgnQQusw',
    '📮': ''
  },
  {
    name: 'Litecoin Summit, Las Vegas',
    startDate: 'October 21, 2022',
    endDate: 'October 22, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://www.litecoin.net/summit',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@litecoin.net',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/LTCFoundation',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'CoinAgenda Global, Las Vegas',
    startDate: 'October 21, 2022',
    endDate: 'October 23, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://coinagenda.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/CoinAgenda',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Money20/20 USA, Las Vegas',
    startDate: 'October 23, 2022',
    endDate: 'October 26, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://us.money2020.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@money2020.com',
    LinkedIn: 'https://www.linkedin.com/company/money2020/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/money2020',
    Youtube: 'https://www.youtube.com/c/Money2020Tv',
    '📮': ''
  },
  {
    name: 'EthPanamá',
    startDate: 'October 26, 2022',
    endDate: 'October 28, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://devcon.org/en/devcon-week/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: 'https://t.me/EthPanama',
    Twitter: 'https://twitter.com/ethpanama',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Tampa Blockchain Conference, Tampa  Florida',
    startDate: 'October 27, 2022',
    endDate: 'October 29, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://layer1con.com',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'ETHLisbon',
    startDate: 'October 28, 2022',
    endDate: 'October 30, 2022',
    location: 'Lisbon',
    image:
      'https://pbs.twimg.com/profile_images/1176181381380149248/aoUEItf2_400x400.jpg',
    conferenceUrl: 'https://www.ethlisbon.org/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/yKpUEh3Tad',
    Email: '',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: 'https://t.me/nearcon',
    Twitter: 'https://twitter.com/ETHLisbon',
    Youtube: '',
    '📮': 'twitter'
  },
  {
    name: 'NFT San Francisco Conference',
    startDate: 'October 30, 2022',
    endDate: 'October 31, 2022',
    location: 'San Francisco',
    image:
      'https://gritdaily.com/wp-content/uploads/2022/08/Black-BG-NFT-San-Francisco-Logo.jpg',
    conferenceUrl: 'https://nftsanfrancisco.org/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/nft-san-francisco-conference',
    Suitable: 'Yes',
    Telegram: 'https://t.me/+y2xc-HXFAM42MzJh',
    Twitter: 'https://twitter.com/NFTSFConference',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'Filecoin Lisbon',
    startDate: 'October 30, 2022',
    endDate: 'November 4, 2022',
    location: 'Lisbon',
    image:
      'https://gritdaily.com/wp-content/uploads/2022/08/Black-BG-NFT-San-Francisco-Logo.jpg',
    conferenceUrl: 'https://hub.fil.org/fil-lisbon',
    latitude: 38.70418445811948,
    longitude: -9.178830084655376,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'events@fil.org',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/FilFoundation',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'SF Blockchain Week, San Francisco',
    startDate: 'October 31, 2022',
    endDate: 'November 6, 2022',
    location: 'San Francisco and Berkeley',
    image:
      'https://pbs.twimg.com/profile_images/1528805671734493184/lzssHLUK_400x400.jpg',
    conferenceUrl: 'https://sfblockchainweek.io/',
    latitude: '',
    longitude: '',
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@sfblockchainweek.io',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/SFBWofficial',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'MoneyConf, Lisbon, Portugal',
    startDate: 'November 1, 2022',
    endDate: 'November 4, 2022',
    location: 'Lisbon',
    image: 'https://startacus.net/uploads/image/MoneyConf.png',
    conferenceUrl: 'https://websummit.com/tracks/moneyconf',
    latitude: 38.76872357617956,
    longitude: -9.093954600200632,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'http://info@websummit.com/',
    LinkedIn: 'https://www.linkedin.com/company/web-summit',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/websummit',
    Youtube: 'https://www.youtube.com/websummit',
    '📮': ''
  },
  {
    name: 'WOW Summit, Lisbon, Portugal',
    startDate: 'November 1, 2022',
    endDate: 'November 3, 2022',
    location: 'Lisbon',
    image:
      'https://media-exp1.licdn.com/dms/image/C4D0BAQGPlrTsWdJCqA/company-logo_200_200/0/1628770562719?e=1675296000&v=beta&t=dmm6jpNbbY9n2yMePgNhpqkFgWoJBbVbmPIqNZ8BOpY',
    conferenceUrl: 'https://wowsummit.net/lisbon-nov-2022/',
    latitude: 38.69664375792793,
    longitude: -9.191469224842388,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'INFO@WOWSUMMIT.NET',
    LinkedIn: 'https://www.linkedin.com/showcase/wow-summit-world/',
    Suitable: 'No',
    Telegram: 'https://t.me/wowsummitworld',
    Twitter: 'https://twitter.com/wowsummitworld',
    Youtube: 'https://www.youtube.com/channel/UCooGWgLOF9sHQo69GhLmY2w/videos',
    '📮': ''
  },
  {
    name: 'Solana Hacker House, Lisbon',
    startDate: 'November 1, 2022',
    endDate: 'November 3, 2022',
    location: 'Lisbon',
    image:
      'https://pbs.twimg.com/profile_images/1562497011257147392/J5HPlqpX_400x400.jpg',
    conferenceUrl: 'https://solana.com/events/lisbon-hacker-house',
    latitude: 38.719031797419575,
    longitude: -9.146581357874188,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/hackerhouses',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'LA BLOCKCHAIN SUMMIT',
    startDate: 'November 1, 2022',
    endDate: 'November 3, 2022',
    location: 'Los Angeles',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.UzAfqK7mQYYxZQJhTcTbdgHaHa%26pid%3DApi&f=1&ipt=d1ed9f65962e9933356a78924431dc2d1ef1496c4cb7573673351bd0d14933bc&ipo=images',
    conferenceUrl: 'https://lablockchainsummit.com/',
    latitude: 34.04049848810362,
    longitude: -118.26953021565396,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/lablockchainsummit',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/lablockchainsmt',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'WebSummit, Lisbon',
    startDate: 'November 1, 2022',
    endDate: 'November 4, 2022',
    location: 'Lisbon',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Web_Summit_logo.svg/1200px-Web_Summit_logo.svg.png',
    conferenceUrl: 'https://websummit.com/',
    latitude: 38.76872357617956,
    longitude: -9.093954600200632,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@websummit.com',
    LinkedIn: 'https://www.linkedin.com/company/web-summit',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/WebSummit',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHSanFrancisco (ETH Global)',
    startDate: 'November 3, 2022',
    endDate: 'November 5, 2022',
    location: 'San Francisco',
    image:
      'https://pbs.twimg.com/profile_images/1333830155287097349/rGY9wviF_400x400.jpg',
    conferenceUrl: 'https://sf.ethglobal.com/',
    latitude: 37.80296046986873,
    longitude: -122.44843382883616,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': 'kartik@ethglobal.com',
    Connection: 'In touch',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@ethglobal.com partner@ethglobal.com',
    LinkedIn: 'https://www.linkedin.com/company/ethglobal/',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHSanFrancisco https://twitter.com/ETHGlobal',
    Youtube: 'https://www.youtube.com/c/ETHGlobal/',
    '📮': 'email'
  },
  {
    name: 'NFTLondon',
    startDate: 'November 3, 2022',
    endDate: 'November 4, 2022',
    location: 'London',
    image:
      'https://media-exp1.licdn.com/dms/image/C4E0BAQH4rX-EwD4RwA/company-logo_200_200/0/1661457119154?e=1675296000&v=beta&t=jMKUqbHfxEZ82ozkv1LXQLMdZ7V9N-WHPUkePTz_vz4',
    conferenceUrl: 'https://www.nft.london/',
    latitude: 51.500360324956816,
    longitude: -0.12906177285717715,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.com/invite/g3vzM2SKPd',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/nft-nyc/',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/NFT_NYC',
    Youtube: 'https://www.youtube.com/c/NFTNYC',
    '📮': 'twitter'
  },
  {
    name: 'Solana Breakpoint, Lisbon',
    startDate: 'November 4, 2022',
    endDate: 'November 7, 2022',
    location: 'Lisbon',
    image:
      'https://media-exp1.licdn.com/dms/image/sync/C4E27AQHXXMoU-SnjPw/articleshare-shrink_800/0/1667115706713?e=1667754000&v=beta&t=Wljzgw_3TdGnFbXNWOPG6N54QahoOMgTs8GIS-wXKrU',
    conferenceUrl: 'https://solana.com/breakpoint',
    latitude: '',
    longitude: '',
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.com/invite/pquxPsq',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/+BrrzvVWk8WA1YzBh',
    Twitter: 'https://twitter.com/SolanaConf',
    Youtube: 'https://www.youtube.com/c/SolanaFndn',
    '📮': ''
  },
  {
    name: 'The Staking Summit, Lisbon, Portugal',
    startDate: 'November 8, 2022',
    endDate: 'November 8, 2022',
    location: 'Lisbon',
    image:
      'https://cdn-az.allevents.in/events5/banners/f4d147b27302331c4a38de34b61dfa2ef29c0efbc9c133305bf9ecaa103ffbfb-rimg-w400-h400-gmir.jpg?v=1665044978',
    conferenceUrl: 'https://www.stakingrewards.com/summit/',
    latitude: 38.70361509731157,
    longitude: -9.178808629038393,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/EqDF9GF',
    Email: 'info@stakingrewards.com',
    LinkedIn: 'https://www.linkedin.com/company/stakingrewards/',
    Suitable: 'No',
    Telegram: 'https://t.me/stakingrewards',
    Twitter: 'https://twitter.com/stakingrewards',
    Youtube: 'https://www.youtube.com/c/StakingRewards',
    '📮': ''
  },
  {
    name: 'Blockchain Revolution Global, Toronto Canada',
    startDate: 'November 8, 2022',
    endDate: 'November 9, 2022',
    location: 'Toronto',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.a28XoxqXsGCgk8Gro3RNEgAAAA%26pid%3DApi&f=1&ipt=b536c9e7c5cbc5423f1f9026386a8a91255eb8ee6cd3d1120a2a874f009aea66&ipo=images',
    conferenceUrl: 'https://blockchainrevolutionglobal.com/',
    latitude: 43.64395702284377,
    longitude: -79.38663634229252,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/blockchain-revolution-global/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/rev_global',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Blockchain Economy Summit, London, UK',
    startDate: 'November 9, 2022',
    endDate: 'November 10, 2022',
    location: 'London',
    image: 'https://pbs.twimg.com/media/FgJQeNkXkAIKdre?format=jpg&name=4096x4096',
    conferenceUrl: 'https://blockchaineconomy.london/',
    latitude: '',
    longitude: '',
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@teklip.org',
    LinkedIn: 'https://www.linkedin.com/company/teklip',
    Suitable: 'No',
    Telegram: 'https://t.me/BE2020_Istanbul',
    Twitter: 'https://twitter.com/BEconomy_HQ?s=20',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Freedom Business Summit (online)',
    startDate: 'November 9, 2022',
    endDate: 'November 10, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://freedomsummit.net/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Token2049, London',
    startDate: 'November 9, 2022',
    endDate: 'November 10, 2022',
    location: 'London',
    image:
      'https://pbs.twimg.com/profile_images/1499252707957248002/jYiiqWGa_400x400.jpg',
    conferenceUrl: 'https://www.europe.token2049.com/',
    latitude: 51.48697854752973,
    longitude: 0.007568245970635927,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@token2049.com',
    LinkedIn: 'https://www.linkedin.com/company/token2049/',
    Suitable: 'No',
    Telegram: 'https://t.me/token2049official',
    Twitter: 'https://twitter.com/token2049',
    Youtube: 'https://www.youtube.com/c/TOKEN2049',
    '📮': 'email'
  },
  {
    name: 'Blockchain for Governance',
    startDate: 'November 10, 2022',
    endDate: 'November 11, 2022',
    location: 'Barcelona',
    image:
      'https://pbs.twimg.com/profile_images/1419625222370639876/_DYEgzFi_400x400.jpg',
    conferenceUrl: 'https://www.d4a.io/',
    latitude: 41.39069700005786,
    longitude: 2.1681518887472317,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'd4a@cbcat.io',
    LinkedIn: 'https://www.linkedin.com/company/bcnblockchainweek/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/D4Aconf',
    Youtube:
      'https://www.youtube.com/channel/UC3UKGPCLRmdCmXbV2EXYqqA/videos?view_as=subscriber',
    '📮': ''
  },
  {
    name: 'World Blockchain Summit, Canada Toronto',
    startDate: 'November 10, 2022',
    endDate: 'November 11, 2022',
    location: 'Toronto',
    image:
      'https://pbs.twimg.com/profile_images/1554003083524333569/HuPoZiCC_400x400.jpg',
    conferenceUrl: 'https://worldblockchainsummit.com/canada/index',
    latitude: '',
    longitude: '',
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@worldblockchainsummit.com',
    LinkedIn: 'https://www.linkedin.com/company/tresconglobal/',
    Suitable: 'Yes',
    Telegram: 'https://t.me/worldblockchainsummit',
    Twitter: 'https://twitter.com/tresconglobal',
    Youtube: 'https://www.youtube.com/channel/UC3ItPPc9UdFxo0-zx2oNOfQ',
    '📮': 'email'
  },
  {
    name: 'Latin American Bitcoin & Blockchain Conference, Buenos Aires Argentina',
    startDate: 'November 11, 2022',
    endDate: 'November 13, 2022',
    location: 'Buenos Aires',
    image:
      'https://pbs.twimg.com/profile_images/1561753375913410561/WMjzFxmw_400x400.jpg',
    conferenceUrl: 'https://www.labitconf.com/',
    latitude: -34.570554299422284,
    longitude: -58.39642071861479,
    Region: 'South America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/labitconf/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/labitconf',
    Youtube: 'https://www.youtube.com/c/LABITCONF',
    '📮': ''
  },
  {
    name: 'ETH Brno, Czech Republic',
    startDate: 'November 11, 2022',
    endDate: 'November 13, 2022',
    location: 'Brno',
    image: 'https://ethbrno.cz/_app/immutable/assets/logo_black-c9170502.svg',
    conferenceUrl: 'https://ethbrno.cz/',
    latitude: 49.19013052601141,
    longitude: 16.62059915767231,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHBrno',
    Youtube: '',
    '📮': 'twitter'
  },
  {
    name: 'Arab Blockchain Week 2022, online',
    startDate: 'November 11, 2022',
    endDate: 'November 18, 2022',
    location: '',
    image:
      'https://pbs.twimg.com/profile_images/1381922948643237889/y8nO93mT_400x400.jpg',
    conferenceUrl: 'https://www.arabblockchainweek.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/arabbcweek',
    Suitable: 'No',
    Telegram: 'https://t.me/arabblockchainweek',
    Twitter: 'https://www.twitter.com/arabbcweek',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Ghana Crypto & DeFi Summit 2022, Accra Ghana',
    startDate: 'November 12, 2022',
    endDate: 'November 12, 2022',
    location: 'Accra',
    image:
      'https://media.licdn.com/dms/image/C4E0BAQHwrdXGYWJnMw/company-logo_200_200/0/1614085053153?e=1675296000&v=beta&t=-wT_u4NjNCy7hHtoAxeLVi5n3wAr5PzA9EU-5qW5Q9g',
    conferenceUrl: 'https://defiafrica.net/ https://afrideficon.live/',
    latitude: 5.600803825940029,
    longitude: -0.17630955830300693,
    Region: 'Africa',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@afrideficon.live',
    LinkedIn: 'https://www.linkedin.com/company/defi-africa/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/defiafrica',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'Istanbul Blockchain Week',
    startDate: 'November 14, 2022',
    endDate: 'November 17, 2022',
    location: 'Istanbul',
    image:
      'https://pbs.twimg.com/profile_images/1539562742222315520/dovsnGed_400x400.jpg',
    conferenceUrl: 'https://istanbulblockchainweek.com/',
    latitude: 41.05855122538183,
    longitude: 28.97952280266949,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@istanbulblockchainweek.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/IstanbulBlockchainWeek',
    Twitter: 'https://twitter.com/IstanbulBlockWk',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'AIBC Europe, Malta',
    startDate: 'November 14, 2022',
    endDate: 'November 18, 2022',
    location: 'Malta',
    image:
      'https://pbs.twimg.com/profile_images/1318829231485472768/sIc55Bcv_400x400.jpg',
    conferenceUrl: 'https://aibc.world/europe/',
    latitude: 35.92218312366089,
    longitude: 14.493210206588133,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/aibcsummit',
    Suitable: 'No',
    Telegram: 'https://t.me/maltablockchainsummit',
    Twitter: 'https://twitter.com/aibcsummit',
    Youtube: 'https://www.youtube.com/AIBCsummit',
    '📮': ''
  },
  {
    name: 'Phocuswright Conference, Phoenix, Arizona',
    startDate: 'November 14, 2022',
    endDate: 'November 17, 2022',
    location: 'Phoenix',
    image:
      'https://pbs.twimg.com/profile_images/1569319159376273412/nPivIrgl_400x400.png',
    conferenceUrl: 'https://www.phocuswrightconference.com/',
    latitude: '',
    longitude: '',
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'events@phocuswright.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/phocuswright/',
    Youtube: 'http://www.youtube.com/user/PhoCusWright/videos/',
    '📮': 'email'
  },
  {
    name: 'Slush, Helsinki Finland',
    startDate: 'November 17, 2022',
    endDate: 'November 18, 2022',
    location: 'Helsinki',
    image:
      'https://pbs.twimg.com/profile_images/1493605732524122121/Xf15QSjb_400x400.jpg',
    conferenceUrl: 'https://www.slush.org/events/helsinki/',
    latitude: 60.2032723776623,
    longitude: 24.936527088514133,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@slush.org partners@slush.org',
    LinkedIn: 'https://www.linkedin.com/company/slush',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/SlushHQ',
    Youtube: 'https://www.youtube.com/c/slush/',
    '📮': 'email'
  },
  {
    name: 'WEB3Dubai',
    startDate: 'November 17, 2022',
    endDate: 'November 18, 2022',
    location: 'Dubai',
    image:
      'https://pbs.twimg.com/profile_images/1538142374710370307/ypNCNrcn_400x400.jpg',
    conferenceUrl: 'https://www.web3dubai.org/',
    latitude: 25.24916857137296,
    longitude: 55.347140014729895,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'Web3Dubai@eventlama.com',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: 'https://t.me/Web3Dubai',
    Twitter: 'https://twitter.com/Web3Dubai',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHGathering, Barcelona',
    startDate: 'November 18, 2022',
    endDate: 'November 20, 2022',
    location: 'Barcelona',
    image:
      'https://pbs.twimg.com/profile_images/1574412861677395970/VMl5tD3A_400x400.jpg',
    conferenceUrl: 'https://www.ethgathering.com/',
    latitude: 41.385927547892116,
    longitude: 2.123303986886244,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@ethgathering.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/+mODbQhmM8iwyMmVk',
    Twitter: 'https://twitter.com/ethgathering',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Web3 Weekend (ETH Global), online',
    startDate: 'November 18, 2022',
    endDate: 'November 20, 2022',
    location: '',
    image: '',
    conferenceUrl: 'https://web3weekend.ethglobal.com/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'In touch',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'partner@ethglobal.com',
    LinkedIn: 'https://www.linkedin.com/company/ethglobal/',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHGlobal',
    Youtube: 'https://www.youtube.com/c/ETHGlobal/',
    '📮': 'email'
  },
  {
    name: 'Next Block Expo, Berlin',
    startDate: 'November 23, 2022',
    endDate: 'November 24, 2022',
    location: 'Berlin',
    image:
      'https://pbs.twimg.com/profile_images/1531925670892273668/7WK-qcPe_400x400.jpg',
    conferenceUrl: 'https://nextblockexpo.com/',
    latitude: 52.4985151207978,
    longitude: 13.374689079115022,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': 'mailto:wojtek@nextblockexpo.com',
    Connection: 'No',
    'Contact person (CP)': 'Anna Weber',
    Discord: '',
    Email: 'support@nextblockexpo.com',
    LinkedIn: 'https://www.linkedin.com/company/next-block-expo',
    Suitable: 'No',
    Telegram: 'https://t.me/nbxchat',
    Twitter: 'https://twitter.com/nextblockexpo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHVietnam',
    startDate: 'November 25, 2022',
    endDate: 'November 27, 2022',
    location: 'Ho Chi Minh',
    image:
      'https://images.squarespace-cdn.com/content/v1/629856e64f44db3799f8e3f6/c9cd11dc-38ee-482f-9084-5340e6adddc7/Symbol+ETHVietnam.png?format=750w',
    conferenceUrl: 'https://www.eth-vietnam.com/',
    latitude: 10.777090300995187,
    longitude: 106.69542599600047,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/mbq747sd3A',
    Email: 'contact@eth-vietnam.com',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: 'https://t.me/ETHVietnamofficial',
    Twitter: '',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Immersive Tech Week 2022, Rotterdam',
    startDate: 'November 28, 2022',
    endDate: 'December 2, 2022',
    location: 'Rotterdam',
    image: 'https://vrdays.co/wp-content/themes/vrdays-2022/assets/img/ITW.svg',
    conferenceUrl: 'https://vrdays.co/',
    latitude: 51.92167327107176,
    longitude: 4.473056738013032,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@vrdays.co',
    LinkedIn: 'https://www.linkedin.com/company/dutch-vr-days/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/VRDays',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'DCentral Miami',
    startDate: 'November 28, 2022',
    endDate: 'November 29, 2022',
    location: 'Miami',
    image:
      'https://cdn1.telegram-cdn.org/file/uzsATZnTbBxFclybYNb82z86ELj4QakLnWFqLDwVEBB9hnPX94rO1daUn1SmRT_UltVhL0EPzO6q8WLJjR4PuSC-o7-FWvy7etv6hl7pvr_qAIu4jfhoqZfYoY-0fSjAQWmR6O9dLnRF3_AAW9J3qLmSTh7MoPtod5xObAyefazACvj1J1rLkDR8WIe89mRCYJgTpEmt9F7Q11XvF06kfAs48GxBkiPc1KrfzYhOfv9pDKMCBemd6RExznGiWCPJf4NZTSy_qKAV-fBmViuGEHP8v1m0sVlL7FLL-EWxLKZbAD8dlGGVSWtthIJqFVnPSLrFrTDLKhTDKm8oFnZFoA.jpg',
    conferenceUrl: 'https://www.dcentralcon.com/',
    latitude: 25.77093427561186,
    longitude: -80.19108249838554,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/DeFiSummit',
    Twitter: 'https://twitter.com/DcentralCon',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'https://cryptoevents.global/miamiweb3-conference-2022/',
    startDate: 'November 28, 2022',
    endDate: 'November 30, 2022',
    location: 'Miami',
    image: 'https://pbs.twimg.com/media/FgiriT2VQAEoi_m?format=png&name=900x900',
    conferenceUrl: 'https://miamiweb3.com/',
    latitude: 25.77220544210223,
    longitude: -80.18590275174715,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/73839719',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/atlasweb3group',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'sub0 2022|The Polkadot Developer Conference',
    startDate: 'November 28, 2022',
    endDate: 'November 29, 2022',
    location: 'Lisbon',
    image:
      'https://imgix.revue.co/profiles/images/000/424/516/original/KTxlFVah.jpg?ixlib=rails-3.1.0&w=168&h=168',
    conferenceUrl: 'https://sub0.polkadot.network/',
    latitude: 38.703502940496165,
    longitude: -9.178874439823513,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://discord.gg/polkadot',
    Email: 'sub0@polkadot.network',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Polkadot',
    Youtube: 'https://www.youtube.com/c/PolkadotNetwork',
    '📮': ''
  },
  {
    name: 'Blockchain Life Dubai',
    startDate: 'November 28, 2022',
    endDate: 'November 29, 2022',
    location: 'Dubai',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.KCFYzZsZyoesOvj9cQw7awHaHa%26pid%3DApi&f=1&ipt=1644add85c289e3304a5d3c7a68101d6f0546f5577d010b4a52a435c90a72bf4&ipo=images',
    conferenceUrl: 'https://blockchain-life.com/asia/en/',
    latitude: 25.13042760732867,
    longitude: 55.1171565266774,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'support@blockchain-life.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/blockchainlifeEN',
    Twitter: 'https://twitter.com/BlLife_Forum',
    Youtube: 'https://www.youtube.com/channel/UCWmwg8fsoOXmW0-xAFXFeWQ/featured',
    '📮': 'email'
  },
  {
    name: 'Web3 Summit NFT2022 Miami',
    startDate: 'November 29, 2022',
    endDate: 'November 30, 2022',
    location: 'Miami',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.FXY1f1xe8PUU5UU2tHViJQHaHa%26pid%3DApi&f=1&ipt=b1333ba1128faf9e50032f48419b027ce3009c994b6affbc7c561b6a48928f30&ipo=images',
    conferenceUrl: 'https://www.web3summits.io/',
    latitude: 25.779173858645965,
    longitude: -80.30944283380073,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/in/kimberli-bruce-b88853ab',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Web3summits',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'FinTech Connect 2022, London',
    startDate: 'November 30, 2022',
    endDate: 'December 1, 2022',
    location: 'London',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.openbankproject.com%2Fwp-content%2Fuploads%2F2019%2F01%2Ffintech-connect.png&f=1&nofb=1&ipt=d9d7670d6e992bc7ca084461d21d0d6a0267aebab9bebc22a0e66611852041d7&ipo=images',
    conferenceUrl: 'https://www.fintechconnect.com/events-london',
    latitude: 51.5084658430183,
    longitude: 0.029847593969764597,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@alphaevents.com',
    LinkedIn: 'https://www.linkedin.com/company/fintech-connect-ltd/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/fintech_connect',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Art Basel Miami Beach',
    startDate: 'December 1, 2022',
    endDate: 'December 3, 2022',
    location: 'Miami',
    image:
      'https://media-exp1.licdn.com/dms/image/C4E0BAQEaA25yEPkykQ/company-logo_200_200/0/1543169732418?e=1675296000&v=beta&t=eZ2BMb0ac9L0NGRnijpOKBrj1l4rDseQ3azFKf-qdGI',
    conferenceUrl: 'https://www.artbasel.com/miami-beach',
    latitude: 25.794766560926252,
    longitude: -80.13378726131623,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@artbasel.com',
    LinkedIn: 'https://www.linkedin.com/company/art-basel',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ArtBasel',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Blockchain Expo Global, London',
    startDate: 'December 1, 2022',
    endDate: 'December 2, 2022',
    location: 'London',
    image:
      'https://blockchain-expo.com/global/wp-content/uploads/2020/01/blockchain-icon.png',
    conferenceUrl: 'https://blockchain-expo.com/global/',
    latitude: 51.496365132709364,
    longitude: -0.21076323934811675,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'blockchain@techexevent.com',
    LinkedIn: 'https://www.linkedin.com/groups/8267411',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/Blockchain_Expo',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'ETHTaipei',
    startDate: 'December 1, 2022',
    endDate: 'December 3, 2022',
    location: 'Taipei',
    image:
      'https://pbs.twimg.com/profile_images/1333830155287097349/rGY9wviF_400x400.jpg',
    conferenceUrl: 'https://www.meetup.com/Taipei-Ethereum-Meetup/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'eth.taipei@gmail.com',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/eth_taipei',
    Youtube: 'https://www.youtube.com/channel/UCVmRAQeesq4TA3rdvbz-IkQ',
    '📮': 'email'
  },
  {
    name: 'ETHDownUnder (Sydney)',
    startDate: 'December 1, 2022',
    endDate: 'December 4, 2022',
    location: 'Sydney',
    image:
      'https://pbs.twimg.com/profile_images/1498953655344836608/kZFCFr1S_400x400.jpg',
    conferenceUrl: 'https://ethdownunder.com/',
    latitude: '',
    longitude: '',
    Region: 'Oceania',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHDOWNUNDER',
    Youtube: '',
    '📮': 'twitter'
  },
  {
    name: 'ETHIndia (ETH Global)',
    startDate: 'December 2, 2022',
    endDate: 'December 4, 2022',
    location: 'Bengaluru',
    image:
      'https://scontent-mxp2-1.xx.fbcdn.net/v/t1.6435-9/55783856_889148091417275_2167421122411233280_n.png?_nc_cat=110&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=-FBk0wYVySAAX-3S7lb&_nc_ht=scontent-mxp2-1.xx&oh=00_AfAOypM--w0tT0wpck8Ae3bQeR8gy3tBlPfpgP_VCG5dbg&oe=6386361A',
    conferenceUrl: 'https://ethindia.co/',
    latitude: 12.978963030617484,
    longitude: 77.71911312808184,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'In touch',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@ethglobal.com partner@ethglobal.com',
    LinkedIn: 'https://www.linkedin.com/company/ethindia',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/ETHIndiaco',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'CoinAgenda Caribbean 2022, San Juan, PR',
    startDate: 'December 5, 2022',
    endDate: 'December 7, 2022',
    location: 'San Juan',
    image:
      'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F97974348%2F90634651333%2F2%2Foriginal.png?w=225&auto=format%2Ccompress&q=75&sharp=10&s=582161fe9190aa53daba633199da59b7',
    conferenceUrl: 'https://coinagenda.com/coinagenda-caribbean-2022/',
    latitude: 18.443326004613898,
    longitude: -66.01772259523557,
    Region: 'South America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/coinagenda',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/CoinAgenda',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Immerse Global Summit (Miami, Florida)',
    startDate: 'December 5, 2022',
    endDate: 'December 7, 2022',
    location: 'Miami',
    image:
      'https://pbs.twimg.com/profile_images/1445281468754845698/vvIVyShv_400x400.jpg',
    conferenceUrl: 'https://www.immerseglobalnetwork.com/',
    latitude: 25.817846081606955,
    longitude: -80.12271337179476,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'http://www.linkedin.com/company/vr-ar-global-summit',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ImmerseSummit',
    Youtube: 'https://www.youtube.com/c/VRARAssociation/',
    '📮': ''
  },
  {
    name: 'Israel Crypto Conference, Tel Aviv',
    startDate: 'December 7, 2022',
    endDate: 'December 8, 2022',
    location: 'Tel Aviv',
    image:
      'https://pbs.twimg.com/profile_images/1504044140811718667/UFv2gYaz_400x400.jpg',
    conferenceUrl: 'https://www.israelcrypto.io/events/israel-crypto-conference',
    latitude: 32.07449695720606,
    longitude: 34.78231966603415,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@israelcrypto.io',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/israelcryptoio',
    Youtube: 'https://www.youtube.com/channel/UC_ZE7HRbrL4Z1fbIgEyRK0A/videos',
    '📮': ''
  },
  {
    name: 'Taipei Blockchain Week',
    startDate: 'December 12, 2022',
    endDate: 'December 17, 2022',
    location: 'Taipei',
    image:
      'https://media.licdn.com/dms/image/C560BAQF0zULAjtEcXw/company-logo_200_200/0/1660777949378?e=1675296000&v=beta&t=G66REesZf6ne_EfC_I3ccgozC4kpRVLWiY1tksKoZjc',
    conferenceUrl: 'https://www.taipeiblockchainweek.com',
    latitude: 25.046170834787095,
    longitude: 121.54483170769109,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@taipeiblockchainweek.com',
    LinkedIn: 'https://www.linkedin.com/company/buzhidao/',
    Suitable: 'Yes',
    Telegram: '',
    Twitter: 'https://twitter.com/buzhidao_tw',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'MetaVentures (Bangkok, Thailand)',
    startDate: 'December 14, 2022',
    endDate: 'December 15, 2022',
    location: 'Bangkok',
    image:
      'https://media-exp1.licdn.com/dms/image/C560BAQGclS1JTSTUkQ/company-logo_200_200/0/1660821390358?e=1675296000&v=beta&t=kg7soEwfWNjRkofUCFnKK3MBDyRoB_2DYJAN8iOpXTM',
    conferenceUrl: 'https://metaventures.global/',
    latitude: '',
    longitude: '',
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/mv-summit',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/MetaVentures11',
    Youtube: '',
    '📮': 'twitter'
  },
  {
    name: 'Blockchain Expo World 2022, Istanbul',
    startDate: 'December 22, 2022',
    endDate: 'December 25, 2022',
    location: 'Istanbul',
    image:
      'https://media-exp1.licdn.com/dms/image/C4D0BAQE_4wDbjMNR9A/company-logo_200_200/0/1653462090910?e=1675296000&v=beta&t=xjrqbwPQIUcraYZ9qQDabtbqRfRmO_qbIyawfMGt42I',
    conferenceUrl: 'https://blockchainexpoworld.com/',
    latitude: 40.989051352371085,
    longitude: 28.826159585682518,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://linkedin.com/company/blockchainexpoworld',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ExpoBlockchain',
    Youtube: 'https://www.youtube.com/channel/UCcXsXcg-FcGFoAsVYCMtDWA',
    '📮': ''
  },
  {
    name: 'CfC St. Moritz, Switzerland',
    startDate: 'January 11, 2023',
    endDate: 'January 13, 2023',
    location: 'St. Moritz',
    image:
      'https://pbs.twimg.com/profile_images/1186265985982042113/qvo9JeCL_400x400.jpg',
    conferenceUrl: 'https://cfc-stmoritz.com',
    latitude: 46.49765454035619,
    longitude: 9.841239398153936,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@cfc-stmoritz.com',
    LinkedIn: 'https://www.linkedin.com/company/cryptofinanceconference/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/CFCstmoritz',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Crypto Conference LA',
    startDate: 'January 13, 2023',
    endDate: 'January 15, 2023',
    location: 'Los Angeles',
    image:
      'https://pbs.twimg.com/profile_images/1564091335233208320/6_u2H4UA_400x400.jpg',
    conferenceUrl: 'https://www.cryptoconference.la/',
    latitude: 33.800885889690015,
    longitude: -117.92092327591249,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@cryptoconference.la',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/CryptoLA2023',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'World Crypto Conference 2023, Switzerland',
    startDate: 'January 13, 2023',
    endDate: 'January 15, 2023',
    location: 'Zürich',
    image:
      'https://pbs.twimg.com/profile_images/1520710593895968770/9RCAm2q4_400x400.jpg',
    conferenceUrl: 'https://worldcryptoconference.org/',
    latitude: '',
    longitude: '',
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@worldcryptoconference.org',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/worldcryptoconference https://t.me/thecrazysuisse',
    Twitter: 'https://twitter.com/WorldCryptoC',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'The Blockchain Event, Fort Lauderdale, Florida',
    startDate: 'February 14, 2023',
    endDate: 'February 17, 2023',
    location: 'Fort Lauderdale',
    image: 'https://pbs.twimg.com/profile_images/714558123500048384/dd5SNmS__400x400.jpg',
    conferenceUrl: 'https://www.theblockchainevent.com/east/',
    latitude: 26.099378880534083,
    longitude: -80.12225102742596,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/groups/8507606/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/BlockchainEvent',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'European Blockchain Convention, Barcelona',
    startDate: 'February 15, 2023',
    endDate: 'February 17, 2023',
    location: 'Barcelona',
    image:
      'https://imgix.revue.co/profiles/images/000/542/198/original/dVwZONhk.jpg?ixlib=rails-3.1.0&w=168&h=168',
    conferenceUrl: 'https://eblockchainconvention.com/',
    latitude: '',
    longitude: '',
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'missgago@eblockchainconvention.com',
    LinkedIn: 'https://www.linkedin.com/company/european-blockchain-convention/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/EBlockchainCon',
    Youtube: 'https://www.youtube.com/channel/UC0hhm0r8FUllvs1gcL2EgFA',
    '📮': ''
  },
  {
    name: 'Block Mountain, Chiangmai, THAILAND',
    startDate: 'February 24, 2023',
    endDate: 'February 25, 2023',
    location: 'Chiangmai',
    image:
      'https://scontent.fmxp12-1.fna.fbcdn.net/v/t39.30808-6/311492361_509727291164548_1014145021559093318_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=vxg1-N2PPnsAX9U6ZFs&_nc_ht=scontent.fmxp12-1.fna&oh=00_AfAQckbg1bGHs_D4KkIPqQhFwogXt9vTdqWeDuVAjEnhCw&oe=636789DE',
    conferenceUrl: 'https://blockmountaincnx.com/',
    latitude: 18.764993206535593,
    longitude: 98.9357260699407,
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'techtalkcnx@gmail.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: 'https://www.youtube.com/channel/UCgTP5n6O0qZDFr9mu1UAQwQ',
    '📮': ''
  },
  {
    name: 'ETHDenver2023',
    startDate: 'February 24, 2023',
    endDate: 'March 5, 2023',
    location: 'Denver',
    image:
      'https://images.squarespace-cdn.com/content/v1/614b990e002ad146a5478e8b/244c7b82-0ee2-45ea-830f-50c450ed2985/ethdenver-spork-logo-pink.png?format=1500w',
    conferenceUrl: 'https://www.ethdenver.com/',
    latitude: 39.78157465589041,
    longitude: -104.97012793038658,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': 'mailto:bas@ethdenver.com',
    Connection: 'Frens',
    'Contact person (CP)': 'Bas Bruinekool (COO)',
    Discord: 'https://discord.gg/sporkdao',
    Email: 'hello@ethdenver.com',
    LinkedIn: 'https://www.linkedin.com/company/ethdenver/',
    Suitable: 'Yes',
    Telegram: 'https://t.me/ETHDenver',
    Twitter: 'https://twitter.com/EthereumDenver',
    Youtube: 'https://www.youtube.com/c/ETHDenver',
    '📮': 'email'
  },
  {
    name: 'Future Digital Finance, Austin, TX',
    startDate: 'March 6, 2023',
    endDate: 'March 7, 2023',
    location: 'Austin',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.IILQ4YJs39B4jq3XfWeX6gHaF3%26pid%3DApi&f=1&ipt=b47fb9505b884775b586d2657088bf3feb50e6e6fdc11f429b4cfda960b5f229&ipo=images',
    conferenceUrl: 'https://netfinance.wbresearch.com/',
    latitude: 30.260740375261356,
    longitude: -97.7471600122553,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'BLOCKCHAIN AFRICA CONFERENCE, Johannesburg, SOUTH AFRICA',
    startDate: 'March 16, 2023',
    endDate: 'March 17, 2023',
    location: 'Johannesburg',
    image: 'https://blockchainafrica.co/wp-content/uploads/2019/08/BAC2020-LOGO.png',
    conferenceUrl: 'https://blockchainafrica.co/',
    latitude: '',
    longitude: '',
    Region: 'Africa',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'info@blockchainafrica.co',
    LinkedIn: 'https://www.linkedin.com/company/bitcoin-events',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/BlockchainZA',
    Youtube: 'https://www.youtube.com/channel/UCni7PAlyNS0_12H-26DJJ3w',
    '📮': ''
  },
  {
    name: 'Paris Blockchain Week',
    startDate: 'March 20, 2023',
    endDate: 'March 24, 2023',
    location: 'Paris',
    image:
      'https://media-exp1.licdn.com/dms/image/D4E0BAQHGysTJ2Lto2Q/company-logo_200_200/0/1665666474057?e=1675296000&v=beta&t=NhMHiFRKUogQ6nPpestlZuQ9wQ_BWDknJhOe_FumCoE',
    conferenceUrl: 'https://www.parisblockchainweek.com/',
    latitude: 48.86040159902851,
    longitude: 2.3376002720121267,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'contact@blockchainweekparis.com',
    LinkedIn: 'https://www.linkedin.com/company/parisblockchainweek',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/ParisBlockWk',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Consensus 2023, Austin, Texas',
    startDate: 'April 26, 2023',
    endDate: 'April 28, 2023',
    location: 'Austin',
    image:
      'https://pbs.twimg.com/profile_images/1582375337110937600/WY9q_hJ8_400x400.png',
    conferenceUrl: 'https://events.coindesk.com/consensus2023/',
    latitude: 30.262519996003537,
    longitude: -97.74014010275643,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'partnerships@coindesk.com',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': 'typeform'
  },
  {
    name: 'ETH Istanbul\nConference & Hackathon',
    startDate: 'April 27, 2023',
    endDate: 'April 30, 2023',
    location: 'Istanbul',
    image:
      'https://cdn4.telegram-cdn.org/file/N9b_MR5so26VPXzoL1RqJokOhgJa0ilYl2vsMZYJW4R_gVnwe8D76Vh99_OyAIVg1sIweMsDdaDfXTYuiT8mb6t7Pw2vQqzAs8oH3c_tXKQJ0Cg7O36KEFj9ZfmcRPdWAdbWieOWPZDZX3vxWQPXgZrJ-zxlzMRpR08ACBz_MpnnFAtLP-TcPir91IVyPZNLjbZ7YepAi0sJuu4qmzVUzqGejhW4LlgjBybK_HLID9iCYNGEFow4CZjZja-CpFYMvEvb96LhK7thjhN1UemxXXsFmsjyvGQMu0A_xo_XAWsAEN645F7eP824uJNaJ8Oi1emasQZqmL4Cu6yyS-5w4w.jpg',
    conferenceUrl: '',
    latitude: '',
    longitude: '',
    Region: 'Asia',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: '',
    Twitter: '',
    Youtube: '',
    '📮': ''
  },
  {
    name: 'Non Fungible Conference, Lisbon',
    startDate: 'May 24, 2023',
    endDate: 'May 25, 2023',
    location: 'Lisbon',
    image:
      'https://uploads-ssl.webflow.com/617ffc16f2f33ed3b80f5a3f/630ccb43d0b3becb9431b9e1_NFC23_info-2.jpg',
    conferenceUrl: 'https://www.nonfungibleconference.com/',
    latitude: 38.72898888275145,
    longitude: -9.151690479336086,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: '',
    LinkedIn: 'https://www.linkedin.com/company/nfcsummit/',
    Suitable: 'No',
    Telegram: 'https://t.me/+fFoOkb5AxvVlMTc8',
    Twitter: 'https://twitter.com/NFCsummit',
    Youtube: 'https://www.youtube.com/channel/UCUaW-mMpwZeAy2Y2vXhh9Uw',
    '📮': 'typeform'
  },
  {
    name: 'Render ATL, Atlanta',
    startDate: 'May 31, 2023',
    endDate: 'June 2, 2023',
    location: 'Atlanta',
    image:
      'https://imgix.revue.co/profiles/images/000/508/528/original/Lsvki9i6.jpg?ixlib=rails-3.1.0&w=168&h=168',
    conferenceUrl: 'https://www.renderatl.com',
    latitude: 33.76031726862982,
    longitude: -84.39014164519135,
    Region: 'North America',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: 'https://renderatl.com/discord',
    Email: 'hello@renderatl.com',
    LinkedIn: 'https://www.linkedin.com/company/renderatl/',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/RenderATL',
    Youtube: 'https://youtube.com/c/renderatl',
    '📮': 'twitter'
  },
  {
    name: 'TravelTech Show, London',
    startDate: 'June 28, 2023',
    endDate: 'June 29, 2023',
    location: 'London',
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.explicit.bing.net%2Fth%3Fid%3DOIP.KFPuqX-vKUunaGdtUaDunQAAAA%26pid%3DApi&f=1&ipt=a4592a1fd8e67b0637ca41f399e5f575ac1356f8c69153513be3a5277330afcf&ipo=images',
    conferenceUrl: 'https://traveltech-show.com/',
    latitude: 51.508463485075666,
    longitude: 0.029843475797070387,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'hello@traveltech-show.com',
    LinkedIn: 'https://www.linkedin.com/company/travel-tech-show',
    Suitable: 'No',
    Telegram: '',
    Twitter: 'https://twitter.com/TravelTech_Show',
    Youtube: '',
    '📮': 'email'
  },
  {
    name: 'Decentralized',
    startDate: 'November 1, 2023',
    endDate: 'November 3, 2023',
    location: 'Athens',
    image:
      'https://pbs.twimg.com/profile_images/1100328990160666624/db81lwbH_400x400.png',
    conferenceUrl: 'https://www.decentralized.com/',
    latitude: 37.980763401555556,
    longitude: 23.754310997592782,
    Region: 'Europe',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'decentralized@unic.ac.cy',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/decentralizedconference',
    Twitter: 'https://twitter.com/DecentralizedEu',
    Youtube: 'https://www.youtube.com/channel/UCcTmSSIs_rRyUOlQKJZ4lpg',
    '📮': ''
  },
  {
    name: 'ETHMiami (rescheduling)',
    startDate: '',
    endDate: '',
    location: '',
    image:
      'https://pbs.twimg.com/profile_images/1504145697569976330/otablKYY_400x400.jpg',
    conferenceUrl: 'https://ethmiami.net/',
    latitude: '',
    longitude: '',
    Region: '',
    'CP LinkedIn': '',
    'CP Twitter': '',
    'CP email': '',
    Connection: 'No',
    'Contact person (CP)': '',
    Discord: '',
    Email: 'office@ethmiami.net',
    LinkedIn: '',
    Suitable: 'No',
    Telegram: 'https://t.me/+Z8HHn0iAGrozZjZh',
    Twitter: 'https://twitter.com/EthMiami',
    Youtube: '',
    '📮': ''
  }
];

const normalizedEvents = allEvents.map(
  ({ latitude, longitude, name, location, image, startDate, endDate, conferenceUrl }) => {
    const latlon: [number, number] | undefined =
      latitude === '' || longitude === ''
        ? undefined
        : [Number(latitude), Number(longitude)];

    const normalizedEvent = {
      conferenceUrl,
      name: name.trim(),
      location: location.trim(),
      image: image.trim(),
      startDate: startDate.trim(),
      endDate: endDate.trim(),
      ...(latlon && { latlon })
    };

    return normalizedEvent;
  }
);
export const filteredEvents: EventItemType[] = normalizedEvents.filter(
  ({ name, location, image, startDate, endDate }) => {
    const isInPast = endDate && getIsInPast(new Date(endDate));
    const isToday = endDate && getIsToday(new Date(endDate));
    if (
      name !== '' &&
      location !== '' &&
      image != '' &&
      startDate != '' &&
      endDate != '' &&
      !isInPast &&
      !isToday
    ) {
      return true;
    }
  }
);

export const filteredEventsWithCoordinates: EventItemType[] = filteredEvents.filter(
  ({ latlon }) => !!latlon
);
